<?php

declare(strict_types=1);

namespace Spora\Plugins\Zernio\Tools;

use Spora\Plugins\Zernio\Support\ZernioConfig;
use Spora\Services\PrincipalContext;
use Spora\Tools\Attributes\Tool;
use Spora\Tools\Attributes\ToolOperation;
use Spora\Tools\Attributes\ToolParameter;
use Spora\Tools\Attributes\ToolSetting;
use Spora\Tools\ValueObjects\ToolResult;

/**
 * Configure Zernio webhooks so the agent can react to platform events
 * (post published, account disconnected, lead submitted, etc.). Up to 10
 * webhooks per user; each subscribes to a subset of the 35+ available
 * event names. Webhooks are signed with HMAC-SHA256 via the
 * `X-Zernio-Signature` header using the per-webhook `secret`.
 *
 * Mutation operations (create/update/delete) require approval. Read
 * operations (list, logs) do not. `test_webhook` fires a synthetic event
 * to a URL to validate the receiver.
 */
#[Tool(
    name: 'zernio_webhooks',
    description: 'Manage Zernio webhooks: list/create/update/delete webhooks, view delivery logs, and send a test event. Each webhook can subscribe to a subset of events (post.published, account.disconnected, lead.submitted, etc.). Webhooks are signed with HMAC-SHA256 using the per-webhook secret.',
    displayName: 'Zernio Webhooks',
    category: 'social-media',
)]
#[ToolOperation(name: 'list_webhooks', description: 'List all configured webhooks', enabledByDefault: true, requiresApprovalByDefault: false)]
#[ToolOperation(name: 'create_webhook', description: 'Create a new webhook subscription', enabledByDefault: true, requiresApprovalByDefault: true)]
#[ToolOperation(name: 'update_webhook', description: 'Update an existing webhook (partial body)', enabledByDefault: true, requiresApprovalByDefault: true)]
#[ToolOperation(name: 'delete_webhook', description: 'Delete a webhook', enabledByDefault: true, requiresApprovalByDefault: true)]
#[ToolOperation(name: 'get_webhook_logs', description: 'Get delivery logs for webhooks', enabledByDefault: true, requiresApprovalByDefault: false)]
#[ToolOperation(name: 'test_webhook', description: 'Fire a synthetic webhook.test event to a URL', enabledByDefault: true, requiresApprovalByDefault: true)]
#[ToolSetting(key: 'api_key', label: 'Zernio API Key', type: 'password', description: 'Bearer token for the Zernio API. Falls back to the ZERNIO_API_KEY environment variable.', required: false)]
#[ToolSetting(key: 'base_url', label: 'Base URL', type: 'text', description: 'Zernio API base URL (default: https://zernio.com/api/v1).', default: 'https://zernio.com/api/v1')]
#[ToolSetting(key: 'http_timeout', label: 'HTTP Timeout', type: 'text', description: 'Seconds before an HTTP request fails (default: 30).')]
#[ToolParameter(name: 'webhook_id', type: 'string', description: 'Webhook ID (the `_id` from list_webhooks). Required for update_webhook and delete_webhook; optional filter for get_webhook_logs.', required: ['update_webhook', 'delete_webhook'])]
#[ToolParameter(name: 'name', type: 'string', description: 'Webhook name (1-50 chars). Required for create_webhook.', required: ['create_webhook'])]
#[ToolParameter(name: 'url', type: 'string', description: 'HTTPS URL that will receive the webhook events. Required for create_webhook and test_webhook.', required: ['create_webhook', 'test_webhook'])]
#[ToolParameter(name: 'secret', type: 'string', description: 'HMAC-SHA256 secret used to sign the X-Zernio-Signature header. Auto-generated by Zernio if omitted on create.', required: false)]
#[ToolParameter(name: 'events', type: 'array', description: 'Event names to subscribe to (e.g. "post.published", "account.disconnected", "lead.submitted"). At least one required on create.', required: ['create_webhook'], items: ['type' => 'string'])]
#[ToolParameter(name: 'is_active', type: 'boolean', description: 'Whether the webhook is active.', required: false, default: true)]
#[ToolParameter(name: 'custom_headers', type: 'object', description: 'Extra HTTP headers to send with every delivery (e.g. {"Authorization": "Bearer …"}).', required: false)]
#[ToolParameter(name: 'from_date', type: 'string', description: 'ISO-8601 date lower bound for get_webhook_logs.', required: false)]
#[ToolParameter(name: 'to_date', type: 'string', description: 'ISO-8601 date upper bound for get_webhook_logs.', required: false)]
#[ToolParameter(name: 'event_name', type: 'string', description: 'Event name to send for test_webhook (e.g. "webhook.test", "post.published").', required: false)]
final class ZernioWebhooksTool extends AbstractZernioTool
{
    private const SETTINGS_PATH = '/webhooks/settings';

    public function execute(
        array $arguments,
        int $agentId,
        ?int $userId = null,
        ?int $taskId = null,
        ?PrincipalContext $context = null,
    ): ToolResult {
        $ownerId = $context->ownerUserId ?? $userId;
        return $this->withConfig($agentId, $ownerId, fn(ZernioConfig $config): ToolResult => $this->guard(
            fn(): ToolResult => match ($this->getOperationName($arguments)) {
                'create_webhook'   => $this->createWebhook($arguments, $config),
                'update_webhook'   => $this->updateWebhook($arguments, $config),
                'delete_webhook'   => $this->deleteWebhook($arguments, $config),
                'get_webhook_logs' => $this->webhookLogs($arguments, $config),
                'test_webhook'     => $this->testWebhook($arguments, $config),
                default            => $this->jsonResult("Webhooks:\n", $this->client->get(self::SETTINGS_PATH, [], $config)),
            },
        ));
    }

    public function describeAction(array $arguments): string
    {
        return match ($this->getOperationName($arguments)) {
            'create_webhook'   => 'Create a Zernio webhook',
            'update_webhook'   => 'Update Zernio webhook ' . $this->arg($arguments, 'webhook_id'),
            'delete_webhook'   => 'Delete Zernio webhook ' . $this->arg($arguments, 'webhook_id'),
            'get_webhook_logs' => 'Get Zernio webhook delivery logs',
            'test_webhook'     => 'Send a test Zernio webhook event',
            default            => 'List Zernio webhooks',
        };
    }

    /** @param array<string, mixed> $arguments */
    private function createWebhook(array $arguments, ZernioConfig $config): ToolResult
    {
        $payload = $this->webhookWritePayload($arguments);
        $missing = $this->missingCreateField($payload);
        if ($missing !== null) {
            return new ToolResult(false, "create_webhook requires `{$missing}`.");
        }
        return $this->jsonResult("Created webhook:\n", $this->client->post(self::SETTINGS_PATH, $payload, $config));
    }

    /** @param array<string, mixed> $arguments */
    private function updateWebhook(array $arguments, ZernioConfig $config): ToolResult
    {
        $id = $this->requireParam($arguments, 'webhook_id', 'update_webhook requires a webhook_id.');
        if ($id instanceof ToolResult) {
            return $id;
        }
        $payload             = $this->webhookWritePayload($arguments);
        $payload['_id']      = $id;
        return $this->jsonResult("Updated webhook:\n", $this->client->put(self::SETTINGS_PATH, $payload, $config));
    }

    /** @param array<string, mixed> $arguments */
    private function deleteWebhook(array $arguments, ZernioConfig $config): ToolResult
    {
        $id = $this->requireParam($arguments, 'webhook_id', 'delete_webhook requires a webhook_id.');
        if ($id instanceof ToolResult) {
            return $id;
        }
        $this->client->delete(self::SETTINGS_PATH, ['_id' => $id], $config);
        return new ToolResult(true, "Deleted webhook {$id}.", ['webhook_id' => $id]);
    }

    /** @param array<string, mixed> $arguments */
    private function webhookLogs(array $arguments, ZernioConfig $config): ToolResult
    {
        $query = $this->stringMap($arguments, [
            'webhook_id' => 'webhookId',
            'from_date'  => 'fromDate',
            'to_date'    => 'toDate',
        ]);
        return $this->jsonResult("Webhook logs:\n", $this->client->get('/webhooks/logs', $query, $config));
    }

    /** @param array<string, mixed> $arguments */
    private function testWebhook(array $arguments, ZernioConfig $config): ToolResult
    {
        $url   = $this->requireParam($arguments, 'url', 'test_webhook requires a url.');
        if ($url instanceof ToolResult) {
            return $url;
        }
        $event = $this->arg($arguments, 'event_name') ?: 'webhook.test';
        return $this->jsonResult("Test fired:\n", $this->client->post('/webhooks/test', ['url' => $url, 'event' => $event], $config));
    }

    /**
     * @param  array<string, mixed> $arguments
     * @return array<string, mixed>
     */
    private function webhookWritePayload(array $arguments): array
    {
        $payload = $this->stringMap($arguments, [
            'name'   => 'name',
            'url'    => 'url',
            'secret' => 'secret',
        ]);
        if (isset($arguments['events']) && is_array($arguments['events']) && $arguments['events'] !== []) {
            $payload['events'] = array_values($arguments['events']);
        }
        $payload['isActive'] = (bool) ($arguments['is_active'] ?? true);
        if (isset($arguments['custom_headers']) && is_array($arguments['custom_headers'])) {
            $payload['customHeaders'] = $arguments['custom_headers'];
        }
        return $payload;
    }

    /**
     * @param array<string, mixed> $payload
     */
    private function missingCreateField(array $payload): ?string
    {
        foreach (['name', 'url', 'events'] as $required) {
            if (empty($payload[$required])) {
                return $required;
            }
        }
        return null;
    }
}
